CurrentlyBob/bamm-voyage-front-end

src/components/ItineraryCard/ItineraryCard.jsx
Stubbed up itinerary card component
=> add itinerary card component outline

src/components/ItineraryCard/ItineraryCard.jsx, src/components/ItineraryCard/ItineraryCard.module.css
added itinerary card functionality
=> add itinerary card functionality

src/pages/NewItinerary/NewItinerary.jsx
Add new itinerary page functionality
=> add new itinerary page functionality

src/components/NavBar/NavBar.jsx, src/pages/NewItinerary/NewItinerary.jsx
commander - fixed nav bar link to itinerary/new and added submit button to form data on itinerary new page.
=> fix nav bar link to itinerary new and add submit button to form data

src/pages/NewItinerary/NewItinerary.jsx
added city and country to form data on new itinerary page
=> add city and country to form data

src/App.jsx, src/components/FlightCard/FlightCard.jsx, src/components/Flights/Flights.jsx, src/components/NewFlight/NewFlight.jsx, src/components/NewFlight/NewFlight.module.css, src/pages/ItineraryDetails/ItineraryDetails.jsx, src/pages/ItineraryDetails/ItineraryDetails.module.css, src/pages/NewItinerary/NewItinerary.module.css, src/services/itineraryService.js
Added full flight create functionality
=> Flight create

src/pages/ItineraryDetails/ItineraryDetails.jsx, src/pages/ItineraryDetails/ItineraryDetails.module.css, src/pages/NewItinerary/NewItinerary.module.css
updated css to itinerary show view
=> add css outline to itinerary show view

src/pages/EditItinerary/EditItinerary.module.css
stubbed up the css for edit itinerary page
=> add minor css to edit itinerary page

package-lock.json, package.json, src/components/NewAccommodation/NewAccommodation.jsx, src/components/NewFlight/NewFlight.jsx, src/pages/ItineraryDetails/ItineraryDetails.jsx, src/pages/ItineraryDetails/ItineraryDetails.module.css
Add toggle to flight and accommodation forms
=> Toggle form

src/components/NewFlight/NewFlight.jsx, src/pages/EditFlight/EditFlight.jsx
Changed roundtrip to a boolean - checkbox, updated for newFlight and editFlight. and updated the corresponding handle change function to account for checkbox checked property
=> Rountrip boolean

src/components/ItineraryCard/ItineraryCard.module.css, src/components/NewAccommodation/NewAccommodation.jsx, src/pages/ItineraryDetails/ItineraryDetails.jsx, src/pages/ItineraryDetails/ItineraryDetails.module.css
here Bobbo, a comment just for you
=> format toggle to have label on top

src/components/TotalCost/TotalCost.jsx, src/pages/ItineraryDetails/ItineraryDetails.jsx
Hi Commander - I added the flight and hotel cost summation functionality to the itinerary details view.
=> add total itinerary cost for flights and hotels

src/pages/ItineraryDetails/ItineraryDetails.jsx
add .utc to moment for display of itinerary start/end date
=> add .utc to moment

src/components/TotalCost/TotalCost.jsx, src/pages/ItineraryDetails/ItineraryDetails.jsx
Add activity cost to total actual cost formula and made both budget and cost into localestring -en-us
=> Update total cost

src/components/AccommodationCard/AccommodationCard.jsx, src/components/AccommodationCard/AccommodationCard.module.css, src/components/FlightCard/FlightCard.jsx, src/components/NewAccommodation/NewAccommodation.module.css, src/components/NewActivity/NewActivity.module.css, src/components/NewFlight/NewFlight.jsx, src/components/NewFlight/NewFlight.module.css, src/pages/EditFlight/EditFlight.jsx, src/pages/ItineraryDetails/ItineraryDetails.jsx, src/pages/ItineraryDetails/ItineraryDetails.module.css
REmoved round trip boolean from front end, added icons to sections in show view, adjusted various css.
=> Remove rountrip

src/components/FlightCard/FlightCard.jsx, src/components/TotalCost/TotalCost.jsx
=> Update to numbers

src/components/NewAccommodation/NewAccommodation.jsx, src/components/NewAccommodation/NewAccommodation.module.css, src/components/NewActivity/NewActivity.jsx, src/components/NewActivity/NewActivity.module.css, src/components/NewFlight/NewFlight.jsx, src/components/NewFlight/NewFlight.module.css, src/pages/ItineraryDetails/ItineraryDetails.module.css
=> New flight form css

src/pages/NewItinerary/NewItinerary.jsx, src/pages/NewItinerary/NewItinerary.module.css
=> tweak new itinerary form

src/components/NewFlight/NewFlight.module.css, src/pages/EditAccommodations/EditAccommodations.jsx, src/pages/EditAccommodations/EditAccommodations.module.css, src/pages/EditActivity/EditActivity.jsx, src/pages/EditActivity/EditActivity.module.css, src/pages/EditFlight/EditFlight.jsx, src/pages/EditFlight/EditFlight.module.css, src/pages/EditItinerary/EditItinerary.jsx, src/pages/EditItinerary/EditItinerary.module.css, src/pages/NewItinerary/NewItinerary.jsx, src/pages/NewItinerary/NewItinerary.module.css
Updated forms on NewItinerary, EditFlight, EditAccommodation, EditActivity
=> More forms

src/pages/EditItinerary/EditItinerary.jsx, src/pages/NewItinerary/NewItinerary.jsx
made budget required for new itinerary, and added moment to edit itinerary
=> add moment to edit Itinerary dates

src/pages/NewItinerary/NewItinerary.jsx, src/pages/NewItinerary/NewItinerary.module.css
changed new itinerary title in form
=> fix new itinerary form

src/App.css, src/components/ItineraryCard/ItineraryCard.jsx
=> image import change

src/pages/Landing/Landing.module.css, src/pages/Login/Login.jsx, src/pages/NewItinerary/NewItinerary.module.css
=> change landing to color scheme

src/pages/Landing/Landing.jsx, src/pages/Landing/Landing.module.css, src/pages/Login/Login.jsx, src/pages/Login/Login.module.css, src/pages/NewItinerary/NewItinerary.module.css, src/pages/Signup/Signup.jsx, src/pages/Signup/Signup.module.css
=> edit background and form edits to signup and login pages

src/pages/Login/Login.jsx, src/pages/Login/Login.module.css, src/pages/Signup/Signup.jsx, src/pages/Signup/Signup.module.css
=> edit buttons

src/components/ItineraryCard/ItineraryCard.jsx
edit itinerary card to show correct month
=> add .utc to itinerary card to show correct month on card

src/pages/ChangePassword/ChangePassword.jsx, src/pages/ChangePassword/ChangePassword.module.css, src/pages/EditAccommodations/EditAccommodations.module.css, src/pages/EditActivity/EditActivity.module.css, src/pages/EditFlight/EditFlight.module.css, src/pages/EditItinerary/EditItinerary.module.css, src/pages/NewItinerary/NewItinerary.module.css
change opacity to forms & added a background image to change password page
=> change opacity to forms

src/pages/Itineraries/Itineraries.module.css
add flex box to itinerary index
=> fix itinerary flex
